name: comp7015
channels:
  - defaults
dependencies:
  - python=3.10.15
  - pip
  - pip:
      - bayesian-optimization==2.0.0
      - imbalanced-learn==0.12.4
      - imblearn==0.0
      - joblib==1.4.2
      - lightgbm==4.5.0
      - matplotlib==3.9.2
      - notebook==7.2.2
      - numpy==1.26.4
      - pandas==2.2.3
      - scipy==1.12.0
      - seaborn==0.13.2
      - tabulate==0.9.0
      - graphviz==0.20.3